#!/bin/bash

lua /opt/emlua/emlua.lua "$@"
emcc ./emlua.c /lua-${LUA_VERSION}/src/liblua.a \
  -I/lua-${LUA_VERSION}/src \
  -s WASM=1 \
  -O2 \
  -o wasm.js \
  -s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']"

rm ./emlua.c

exit $?
